name: SonarQube analysis with Maven

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      application_module:
        default: 'application'
        type: string
    secrets:
      MVN_GITHUB_USER:
        required: true
      MVN_GITHUB_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  analyze:
    runs-on: [self-hosted, linux, maven]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current date as env variable
        run: |
          echo TIMESTAMP=$(date +'%Y%m%d%H%M%S') >> $GITHUB_ENV
          echo COMMIT_ID=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - name: Build with Maven
        env:
          USENAME: ${{ secrets.MVN_GITHUB_USER }}
          PASSWORD: ${{ secrets.MVN_GITHUB_TOKEN }}
        run:  |
          mvn -B -U -f ${{ inputs.context }} -Drevision=$TIMESTAMP.$COMMIT_ID clean verify --settings .github/settings.xml

      - name: SonarQube analysis
        run: |
          mvn -f ${{ inputs.context }} org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.branch.name=${GITHUB_REF_NAME} \
          --settings .github/settings.xml
